.github/workflows/global-monitoring.yaml

See https://github.com/OCHA-DAP/pa-global-monitoring/issues/12#issue-1769826733

rm caching from global-monitoring.yaml workflow

---

.github/workflows/global-monitoring.yaml

temporarily increasing CRON freq to more quickly find out if the removal of caching action resolves the issue over multiple runs. If resolved WILL return back to previous CRON run freq

temporarily increase CRON freq to make sure caching is resolved

---

.gitignore
NEWS.md
README.md
src/README.md
src/email/email.Rmd
src/indicators/idmc/README.md
src/indicators/idmc/update_idmc.R
src/send_alerts.R
src/utils/email.R
src/utils/flagging.R
src/utils/google_sheets.R

Set up some various improvements to emails based on Sarah's comments. All changes detailed in `NEWS.md`, which I'm also implementing. As I have run from today the emails with these changes (and will continue to run from this branch instead of main until merged), the date is listed as October 3 so that it can be compared with the dates of emails being sent if ever necessary.

Improve emails

---

src/alerts/check_signals_updates.R

The `base_logs_url` variable wasn't defined in the right place.

Fix logs url

---

.gitbook.yaml
docs/README.md

Add GitBook docs

---

README.md

Hotfix logo

---

renv/settings.json
src/indicators/jrc_agricultural_hotspots/utils/wrangle_agricultural_hotspots.R

Re-cloned the repo and new `{renv}` settings seem to update the settings JSON, so that is also included.

Fix agricultural hotspots

---

src/indicators/wfp_market_monitor/utils/raw_market_monitor.R
src/utils/cloud_storage.R

Change terminology

---

src/indicators/acled_conflict/utils/raw_conflict.R

Addressing the errors from https://github.com/ocha-dap/hdx-signals/actions/runs/9561236812

Drop ACLED filtering

---

src/indicators/wfp_market_monitor/update_market_monitor.R
src/signals/check_signals_updates.R
src/signals/generate_signals.R
src/signals/triage_signals.R
src/utils/cloud_storage.R

A couple `test` variable references that snuck in...

Fix references to out of date variable name

---

src/indicators/acled_conflict/utils/summary_conflict.R
src/indicators/idmc_displacement/utils/summary_displacement.R
src/indicators/jrc_agricultural_hotspots/utils/summary_agricultural_hotspots.R

Fixes #176. Testing in [these](https://github.com/OCHA-DAP/hdx-signals/actions/runs/9571472364) [three](https://github.com/OCHA-DAP/hdx-signals/actions/runs/9571468278) [actions](https://github.com/OCHA-DAP/hdx-signals/actions/runs/9571461350).

Fix ai_summarizer calls

---

src-static/update_adm0_sf.R
src/utils/download_shapefile.R

Add iso3 to shapefiles

---

CHANGES.md
src/utils/ai_summarizer.R

Very simple, also ensuring we trim single quotes not just double quotes from AI outputs.

Trim single quotes from AI summaries as well

---

src/images/plots/breaks_date.R

Pushed quickly like a dingle before the lint finished. Now have fixed the lint by ensuring I use the scalar logical operator.

Add scalar condition

---

.github/workflows/user_audience_analysis.yml

just yaml boilerplate so i can work on audience analysis GHA pipeline in `audience-analysis` branch. This boilerplate needs to be merged to main before GitHub recognizes the GHA.
Tagging @hannahker for timezone convenience

audience analysis yaml boiler plate to init gha job on gh

---

.github/workflows/post_slack_update.yaml

very small PR: just changed the CRON job for slack notification to 1 hour earlier.

change slack notification time from 10 am to 9 am

---

.github/workflows/gha_retry_test.yaml

just need to merge this boiler plate to test out the action on another branch

yaml boiler plate to test retry@v3 action

---

docs/README.md

Remove one country from count for food insecurity coverage. In detail, the country removed is MMR

Docs: Update README.md

---

ENVIRONMENT.md

tiny PR. I think we can ignore updating the signals version info for this one
closes #249

add HS_ADMIN_NAME to ENVIRONMENT.md

---

src/indicators/acaps_inform/utils/raw_inform.R

just small tweaks to file paths

fix blobpath for acaps inform parquets

---

docs/PROMPTS.md
src-static/update_indicator_mapping.R
src/indicators/acaps_inform_severity/__init__.R
src/indicators/acaps_inform_severity/prompts/long.txt
src/indicators/acaps_inform_severity/prompts/short.txt
src/indicators/acaps_inform_severity/utils/alert_inform.R
src/indicators/acaps_inform_severity/utils/plot_inform.R
src/indicators/acaps_inform_severity/utils/raw_inform.R
src/indicators/acaps_inform_severity/utils/summary_inform.R
src/indicators/acaps_inform_severity/utils/table_inform.R
src/indicators/idmc_displacement/prompts/short.txt
src/signals/generate_campaign_content.R

- adjust table with alerts displayed
- adjust inform summary

Inform adjustments
