OCHA-DAP/hdx-signals

src/plots/plot_idmc.R, src/run.R, src/utils/google_sheets.R
Simple PR. Want to explicitly specify all the column typing when we load in Google Sheets for the system. Specifying them all in one location in case we load files in separate locations.
=> Explicitly specify column typing

NEWS.md, src/indicators/cholera/update_cholera.R
Closes #37. Checks for 3 alphabetic characters in the date, and if they are present, parses using `dmy()`. If the date was prior to September 25, 2023, the parsing is still done as `dmy()` (since this is how those files have always been parsed. Then, otherwise, it parses as `mdy()`, which is the new format used by the WHO AFRO bulletins.
=> Fix start_dates for cholera

src/indicators/ipc/update_ipc.R, src/utils/ipc_get.R
Temporary hotfix to deal w/ improper type conversion from `{ripc}`. 
Some `_percentage` columns reading as "character" some reading as "numeric" so they can't be bound together.
https://github.com/OCHA-DAP/ripc/issues/7#issue-2154372435
and I've also done a [PR on `{ripc}`](https://github.com/OCHA-DAP/ripc/pull/8) which implements the same quick fix. Nonetheless I recommend we go w/ the internal fix here as a temporary solution for several reasons which I believe all have the same goals of using time most efficiently and reducing potential side-effects:
1. Updating `{ripc}` would require  fast push's to  main on 2 separate repo's without Seths review
2. I have a quick solution here that works in `{ripc}`, but think we can come up w/ a more robust solution for `{ripc}`
3. ripc is on CRAN, …
=> quick-fix for ipc_get type conversion error

src/email/mailchimp/audience.R, src/email/mailchimp/custom_segmentation.R
Pulling in our list of audience members, noticed after our tests today only 10 members were receiving the alerts, turns out that the default return from the Mailchimp API was 10, so have set it up so it automatically pulls in 1,000 by default and paginates through if necessary.
I have previously used `httr2::req_perform_iterative()` with iterator functions, but was too tired to figure out how to do it this time and couldn't see any link follow on in the response object, just `total_items`, so thought this was the best way, but happy for you to suggest/improve!
=> Ensure that we get full list of audience members

src/email/components/hdx_signals_template.html
Changing color of links in email HTML file to match the color in our plots, `gghdx::hdx_hex("sapphire-hdx")`. You can review since you put in the restrictions on the repo, mwahaha.
=> Align email link color with hdx-sapphire color in visualization

src/email/mailchimp/base_api.R, src/indicators/acled_conflict/utils/plot_conflict.R
Given the issues with Mailchimp servers today, implemented some simple retry logic into the API requests. Also made a quick change in ACLED plots as well because was trying to run ACLED with the retry logic during the downtime.
=> Backoff req

src/alerts/create_campaigns.R, src/email/mailchimp/custom_segmentation.R
So, it turns out that updating static segments with a list of emails was not REMOVING emails already on the list. So to fix that, first need to remove the emails to make it empty, then add back the emails we want to send to.
=> Fix test segmentation

src/utils/ai_summarizer.R
Quick fix, no output was being given in the case the `if()` state wasn't evaluated.
=> Add output for short summary function

src/indicators/idmc_displacement/update_displacement.R, src/indicators/idmc_displacement/utils/map_displacement.R
Hardcoded `indicator_id` meant that both disaster related displacement and conflict related displacement were being assigned to conflict related.
=> Hotfix to IDMC because hardcoded indicator_id incorrect

src/indicators/idmc_displacement/utils/plot_displacement.R
Simple change to IDMC plot tile based on feedback from the IDMC. Changes to match the IDMC language on flow monitoring vs stocks found [here](https://www.internal-displacement.org/monitoring-tools/#:~:text=The%20total%20number%20of%20movements,conflict%20or%20violence%20or%20disaster).
=> Adjust text to match IDMC flow language

.Rprofile, src/alerts/generate_signals.R, src/alerts/triage_signals.R, src/indicators/acled_conflict/update_conflict.R, src/indicators/idmc_displacement/update_displacement.R, src/indicators/ipc_food_insecurity/update_food_insecurity.R, src/indicators/jrc_agricultural_hotspots/update_agricultural_hotspots.R, src/utils/ai_summarizer.R, src/utils/get_env.R
Fixes to some issues found in the code.
1. `log_info()` in `generate_signals()` was the final statement, so the logging was the return value, instead of the dataset itself. I didn't think I could find anywhere else where that error existed.
2. I think `test` being unset should always be `TRUE`. Runs should only be done intentionally. Are we sure we don't want `test` to be internal to the function, so we just use the env variable and remove the duplicated calls in each `update_{indicator}.R` script?
3. I have changed it so we only throw errors on warnings when not interactive. This should allow for a lot more flexibility when interactively developing. What do you think?
4. Some other small changes I notice when doing some runs.
=> Hotfix signals return

src/images/plots/theme_signals.R
Set plot and panel background to white. Transparent background ran into issues with dark mode. Not sure if I need to set both, but I believe `plot.background` is limited to plot extents, but `ggsave(..., bg = NULL)` is the default argument and when `bg` is `NULL`, it saves with the value specified as `plot.background`. So figured safer to set both.
=> Setting plot and panel background to white

src/email/components/hdx_signals_template.html
Simple shift to use new logo stored on Mailchimp.
=> Use new logo without the pattern

src-static/update_iso3_sf.R, src/utils/download_shapefile.R
Not actually ready to be merged, but I thought rather than write a bunch of words in issue #111 , easier to just to just write some starter code in a branch to help discuss the approach. Happy to completely adjust approach and/or delete branch as we see fit.
You'll see I just implemented the approach for the Fieldmaps admin 0s as well as the first exception `iso3=ABA` (just put in a placeholder attribution for ABA). If we think it makes sense i can manually enter the attributions for the rest of the exceptions.
Will need to adjust this code potentially as/if we address #114 as well, but it should work in current construction of updating admins
=> init data_source attribution for adm0

.github/workflows/post_slack_update.yaml, check-actions.R, src/alerts/check_signals_updates.R, src/alerts/generate_signals.R, src/alerts/triage_signals.R, src/utils/cloud_storage.R
This PR introduces new functionality to output daily Slack updates on whether any new signals were detected and on the status of the monitoring scripts running in GitHub Actions. See screenshot below for examples of what these messages will look like, or #hdx-signals-bot-testing. 
Closes #64. 
If there are signals: 
If there are no signals:
=> Slack integration

src/alerts/check_existing_signals.R, src/alerts/delete_campaign_content.R, src/alerts/generate_signals.R, src/alerts/triage_signals.R
Previously, `overwrite_content` was a confusing parameter that when passed, meant that you expected existing rows of data in the signals data frame, and you would use those rows to generate new campaign content and signals. That is, you could basically not recalculate when you alert, just adjust how the content looked.
Turns out, this was way too complex, especially since recalculating when we want to alert is simple and easy and local, whereas the expensive computations are already in the content generation side. I've thus removed all of this functionality, and instead we just expect that if a dataset exists in `output/indicator/signals.parquet`, that it must be triaged before any new runs can happen. And if we elect to delete during triage, instead of deleting the content columns, it …
=> Remove overwrite_content functionality

src/utils/cloud_storage.R
Minor change so that we don't have to have the SAS tokens defined when not needed -- for example: https://github.com/OCHA-DAP/hdx-signals/actions/runs/9316443921/job/25644717361
The two functions are somewhat redundant, but I like the ease of calling just `blob_dev()`, for example, and not having to specify all the input parameters.
=> Functionalize connections to Azure blob

renv.lock, src/indicators/jrc_agricultural_hotspots/utils/plot_agricultural_hotspots.R
Added in `fct_expand` + `fct_relevel` to make sure JRC legend always has all 3 factor levels in the same order for plot legend.
closes #130
=> fct_expand + fct_relevel legend order to ensure consistency

src/email/create_user_analytics_dataset.R
added step to remove user interaction data from user interests data.frame prior to checking blob and appending data. I deleted user-interests on blob to start fresh csv with this [run](https://github.com/OCHA-DAP/hdx-signals/actions/runs/12054973407)....
Do we forsee an issue that now we have one extraction date for user interests...but multiple for others? 
i think we could ignore the CHANGES failed test for this
=> remove interaction data from interest data before appending

src/run/run_triage_signals.R
This pull request makes a minor update to the way the `test` parameter is handled in the `triage_signals$triage_signals` function call, ensuring that its value is explicitly converted to a logical type.
=> fix: 🐛 cast `TEST` environment variable to logical

.github/workflows/triage_signals.yaml
Here we just add the HDX BEARER token which is needed for triaging to the yaml (see autogen summary below for more explanation).
This pull request makes a minor update to the GitHub Actions workflow by adding a new secret environment variable to the job configuration.
- Workflow configuration:
* Added the `HS_HDX_BEARER` secret as an environment variable in the `.github/workflows/triage_signals.yaml` workflow file.
Just providing a bit of an explanation on the last triaging for future understanding:
The fixes made here were done in this manner because we didn't have access to the PROD WRITE key so all troubleshooting and "manual" cleaning of files were done via GHA.
1. Aug 5 signals were triaged approved locally. The signals were sent but because local analyst did not have PROD write key …
=> add hdx bearer token to triage yaml
